### ISSUE TITLE
Failed to load plugin 'jest'

### ISSUE THREAD

**Issue by muuvmuuv** [preactjs/eslint-config-preact#5]
I have installed the config in the root of my project and in a sub-directory I have an eslint config, which looks like that:

```json
{
  "root": true,
  "extends": [
    "../.eslintrc.json",
    "preact",
    "plugin:jsx-a11y/recommended"
  ],
  "settings": {
    "react": {
      "createClass": "createElement",
      "pragma": "h"
    }
  },
  "rules": {
    "react/prop-types": "off"
  }
}
```

Now when I do `eslint -c docs/.eslintrc.json --cache docs`. I get this error:

```
ESLint: 6.8.0.

ESLint couldn't find the plugin "eslint-plugin-jest".

(The package "eslint-plugin-jest" was not found when loaded as a Node module from the directory "/Users/marvinheilemann/Development/CookieConsent".)
```

**Comment by muuvmuuv** [comment]
Sorry, just miss read something

**Comment by RyanChristian4427** [comment]
Firstly, check your `node_modules` directory, and see if eslint-plugin-jest is in there.

If not, try deleting your `package-lock.json` file as well as the `node_modules` directory, and then reinstall. Sometimes NPM just won't install all dependencies of dependencies, and this is the fix.

**Comment by muuvmuuv** [comment]
It is not there, because I'm not using jest or any test framework. Why do I need to install something I do not need? Or why does the eslint-config does not install it as a peerDep, seems like it is not working without it.

**Comment by RyanChristian4427** [comment]
I think you're confused, `eslint-plugin-jest` has nothing to do with actually using a testing framework. It's a dependency of this config. Whether you use Jest or not, it comes with this config, and is minimal in size. You shouldn't worry about any bloat with it.

> Or why does the eslint-config does not install it as a peerDep, seems like it is not working without it.

So that's not what peer dependencies are for. This config has `eslint-plugin-jest` as a dependency, it will install that itself. Sometimes, NPM has issues where is just won't though. It gets confused. That's why I told you to delete your `package-lock.json` file, along with your `node_modules`, as that is how you fix it.

**Comment by muuvmuuv** [comment]
Oh, yes, sorry I misunderstood your suggestion! Now it seems to work (still the babel issue but this is another issue). Thank you!

**Comment by REENA1101** [comment]
My Error is: "[eslint] Failed to load plugin 'jest' declared in 'package.json » eslint-config-react-app/jest': Cannot find module 'eslint/package.json'"

quite a similar one, the only difference is that it says  "Cannot find module 'eslint/package.json' instead of "eslint-plugin-jest
What should I do?
