### ISSUE TITLE
Unexpected end of JSON input Error

### ISSUE THREAD

**Issue by fuadnafiz98** [preactjs/eslint-config-preact#9]
while installing `eslint-config-preact` it shows following error 
```bash
$ sudo npm install -D eslint-config-preact

npm ERR! Unexpected end of JSON input while parsing near '...0"}},"1.0.13":{"name"'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fuadnafiz98/.npm/_logs/2020-06-03T01_03_59_569Z-debug.log
```

**Comment by marvinhagemeister** [comment]
1. Never run `npm` commands with `sudo`. That's a huge security hole, because npm scripts can run anything in `postinstall` scripts. If a malicious packages is installed it can do anything it wants on your system with no restrictions.

2. Just installed `eslint-config-preact` in various node versions and it works fine on my end. From the stack trace you posted it looks like you got a syntax error in your `package.json`. Opening `/home/fuadnafiz98/.npm/_logs/2020-06-03T01_03_59_569Z-debug.log` will reveal more detals. In any case that's not an issue with `eslint-config-preact`.
